
name: Continuous Deployment

on:
  push:
    branches: [ "main" ]

jobs:
  deploy:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4 
    - run: docker build . -t vsahni/sih-disaster-management
    # - run: docker build Backend -t vsahni/SC-Backend
    - run: echo "${{secrets.DOCKERHUB_SECRET}}" | docker login -u ${{secrets.DOCKERHUB_USERNAME}} --password-stdin
    - run: docker push vsahni/sih-disaster-management:latest

 
